---
openapi: 3.0.1
info:
  title: BLOG API V1
  version: v1
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: '2'
        name:
          type: string
          example: Scott Wells
        photo:
          type: string
          example: https://randomuser.me/api/portraits/men/46.jpg
        bio:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras posuere,
            diam eu tempor gravida, tellus nibh accumsan ligula, at efficitur neque
            nibh at tellus. Nullam ante ex, lobortis sit amet odio ac, fermentum cursus
            est. Quisque ornare dapibus metus in eleifend. Ut luctus erat eget mauris
            egestas porta. Suspendisse potenti. Curabitur malesuada nunc ex, ac tincidunt
            purus eleifend nec. Nunc nisi orci, bibendum sit amet orci ac, tempus
            tristique libero. Proin tempor convallis lectus, sed fringilla ex finibus
            vulputate.
        posts_count:
          type: integer
          example: '3'
        email:
          type: string
          example: scott_wells@test.com
    post:
      type: object
      properties:
        id:
          type: integer
          example: '3'
        title:
          type: string
          example: Donec commodo magna vel tortor cursus.
        text:
          type: string
          example: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a urna
            fringilla, cursus elit non, sagittis quam. Orci varius natoque penatibus
            et magnis dis parturient montes, nascetur ridiculus mus. Sed et urna vel
            ante ultrices volutpat et sed risus. Aenean vestibulum urna a metus vestibulum,
            sit amet ornare dui mollis. Pellentesque tincidunt congue lorem quis scelerisque.
            Aenean pellentesque ornare justo sed molestie. Vestibulum sagittis eget
            tortor tincidunt cursus. Nunc ac scelerisque nulla. Aliquam molestie laoreet
            consectetur. Integer viverra nunc at diam accumsan vehicula.\nPraesent
            porta, urna eu consectetur tempor, enim metus porttitor nibh, non hendrerit
            orci dui eu ligula. Maecenas posuere lorem nec mollis iaculis. Suspendisse
            in lorem urna. Nullam sollicitudin erat et eleifend tristique. Duis in
            libero orci. Aliquam quis convallis erat, non cursus erat. Morbi non massa
            nec orci mollis efficitur. Nunc varius nulla sed nisl ultrices dictum.
            Nullam lacinia nisl ac lacinia laoreet. Praesent venenatis sapien ut risus
            ultricies, ac fringilla odio tincidunt. Aliquam nec pretium augue. Nulla
            laoreet mattis mauris, a mattis dui feugiat sed. Aliquam eros dolor, feugiat
            sit amet maximus et, aliquet viverra mi. Suspendisse potenti. Vestibulum
            ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia
            curae;\nQuisque consectetur quam placerat enim lacinia, ac commodo lorem
            rhoncus. Cras enim elit, egestas at commodo nec, molestie sed ante. Morbi
            at venenatis ipsum. Pellentesque varius ac urna quis mattis. Cras accumsan
            libero a dui sodales condimentum. Cras placerat lacus ut nunc condimentum,
            sit amet laoreet augue suscipit. Duis sed eleifend neque, et lobortis
            orci.
        comments_counter:
          type: integer
          example: '11'
        likes_counter:
          type: integer
          example: '0'
    comment:
      type: object
      properties:
        id:
          type: integer
          example: '11'
        text:
          type: string
          example: THANKS EVERYONE
        author:
          "$ref": "#/definitions/User"
    ErrorResponse:
      type: object
      properties:
        type: array
        items:
          type: string
paths:
  "/api/v1/oauth/token":
    post:
      summary: api_token
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "<access_token>"
                  token_type:
                    type: string
                    example: "<token_type>"
                  expires_in:
                    type: number
                    example: 7200
                  refresh_token:
                    type: string
                    example: "<refresh_token>"
                  created_at:
                    type: number
                    example: 1670688261
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  example: fRh5JehDfETFIwzcSdzFNxpFlsEJ6K6cRWzrbpAhCD0
                client_secret:
                  type: string
                  example: 9tFczlstU6TOLSmHzwNEr1iCCoCJJeUTH0w-mBQZVyU
                grant_type:
                  type: string
                  example: password
                email:
                  type: string
                  example: "<user_email>"
                password:
                  type: string
                  example: "<user_password>"
              required:
              - client_id
              - client_secret
              - grant_type
              - email
              - password
  "/api/v1/users":
    get:
      summary: List of Users
      security:
      - bearer_auth: []
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: number
      responses:
        '401':
          description: Unauthorized
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/User"
